package com.kushalarora.compositionalLM.derivatives;

import com.kushalarora.compositionalLM.model.CompositionalInsideOutsideScore;
import com.kushalarora.compositionalLM.model.Model;
import com.kushalarora.compositionalLM.optimizer.IIndexed;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

import org.apache.commons.math3.random.JDKRandomGenerator;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

import java.util.List;

/**
 * Created by karora on 6/21/15.
 * Energy function E is given as
 * E = g(u^Tp) where p is phrase vector..
 * dEdu = g'(u.t().dot(p))p
 * <p/>
 * dQdu = \sum{start}{end}{split} dEdu(start, end, split) * \mu(start, end, split)
 */
@Slf4j
public class dQdu<T extends List<? extends IIndexed>> extends AbstractBaseDerivativeClass implements IDerivative<T> {
    @Getter
    private INDArray dQdu;
    private int dimensions;
    private T data;
    private int length;


    public dQdu(int dim, T data) {
        super(new int[]{dim, 1});
        dQdu = Nd4j.zeros(dim, 1);
        dimensions = dim;
        this.data = data;
        length = data.size();
    }

    public dQdu(dQdu dqdu, T data) {
        super(dqdu.dQdu.shape());
        dQdu = dqdu.dQdu.dup();
        dimensions = dqdu.dQdu.shape()[0];
        this.data = data;
        length = data.size();
    }

    private dQdu(INDArray dqdu, T data) {
        super(dqdu.shape());
        this.dQdu = dqdu;
        dimensions = dqdu.shape()[0];
        this.data = data;
        length = data.size();
    }

    public void clear() {
        // Wipe clean
        for (int i = 0; i < dimensions; i++) {
            dQdu.putScalar(i, 0);
        }
    }

    public void add(IDerivative other) {
        dQdu = dQdu.add(((dQdu) other).getDQdu());
    }

    public void mul(double learningRate) {
        dQdu = dQdu.mul(learningRate);
    }

    public boolean containsNanOrInf() {
        return containsNanOrInf(dQdu);
    }

    public IDerivative adaGrad(IDerivative gradient) {
        return new dQdu(adaGrad.getGradient(((dQdu) gradient).dQdu), data);
    }

    public double norm()
    {
        return Nd4j.norm2(dQdu.sum(Integer.MAX_VALUE)).getFloat(0);
    }

    public void calcDerivative(Model model, CompositionalInsideOutsideScore scorer) {
        INDArray[][][] compositionMatrix = scorer.getCompositionMatrix();
        INDArray[][] phraseMatrix = scorer.getPhraseMatrix();
        double[][][] compositionMu = scorer.getMuScore();
        double[][] compositionalIScore = scorer.getInsideSpanProb();

        // do leaf nodes
        for (int start = 0; start < length; start++) {
            int end = start + 1;
            int split = start;

            // For leaf nodes we consider the phrase
            INDArray phraseVector = phraseMatrix[start][end];

            // dE = g'(u.t().dot(p))
            double dE = model.energyDerivative(phraseVector);

            // dEdu = dE * p = g'(u.t().dot(p)) * p
            INDArray dEdu = phraseVector.muli(dE);

            // dQdu += dEdu * \mu[start][end][split]
            dQdu = dQdu.add(
                    dEdu.muli(
                            compositionMu[start][end][split]));
        }

        for (int diff = 2; diff <= length; diff++) {
            for (int start = 0; start + diff < length; start++) {
                int end = start + diff;
                for (int split = start + 1; split < end; split++) {

                    // Composition vector is parent's(start, end) embedding generated by
                    // child1 (start, split) and child2 (split, end)
                    INDArray compositionVector = compositionMatrix[start][end][split];

                    // dE = g'(u.t().dot(p))
                    double dE = model.energyDerivative(compositionVector);

                    // dEdu = dE * p = g'(u.t().dot(p)) * p
                    INDArray dEdu = compositionVector.muli(dE);

                    // dQdu += dEdu * \mu[start][end][split]
                    dQdu = dQdu.add(
                            dEdu.muli(
                                    compositionMu[start][end][split]));
                }
            }
        }

        if (compositionalIScore[0][length] == 0) {
            throw new RuntimeException("Z is zero for sentence " + data);
        }

        dQdu = dQdu.div(compositionalIScore[0][length]);

        if (containsNanOrInf()) {
            log.error("dQdu contains Nan Or Inf. for data {}", data);
            dQdu = Nd4j.rand(dimensions, 1, -1, 1, new JDKRandomGenerator());
        }
    }
}
